# For standard Spring Boot parameters see:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
server:
  servlet:
    session:
      timeout: 1000


# TODO: REVIEW IF YOUR APPLICATION NEEDS TRACE THIS PARAMETER OR MORE (this is an example with installationNumber)      
# Spring Cloud Sleuth tracing extra fields to propagate (HTTP/Rest and messaging).
spring:  
  sleuth:
    propagation-keys:
    - installationnumber
    log:
      slf4j:
        whitelisted-mdc-keys:  
        - installationnumber
        
  data:
    mongodb:
      database: CSFLE-INSTALLATION
      uri: ${MONGODB_URI}
      key:
        vault:
          database: "encryption"
          collection: "__keyVault"
          name: "dataEncKeyArquetipo"
      kmsprovider: "local"
      encryption:
        #cryptdpath: "/usr/local/bin/mongocryptd"
        masterKeyPath: "master-key.txt"
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration        